version: "3.8"
services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: Dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - /opt/docker/dashy/config/my-config.yml:/app/user-data/conf.yml
      - /opt/docker/dashy/item-icons:/app/user-data/item-icons/
    ports:
      - 3300:8080
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - UID=1000
      - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - tunnel #the name of our Cloudflare Zero Trust Tunnel Docker's Network

networks:
  tunnel: #this is the name of the network that we created in the Cloudflared Container
    external: true #we already created it!
